services:
  # Backend API Service
  - type: web
    name: medical-rag-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        fromDatabase:
          name: medical-rag-db
          property: connectionString
      # Add your other backend env vars here

  # Frontend Static Site
  - type: web
    name: medical-rag-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html